# Generated by Django 6.1 on 2026-08-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(blank=True, default='استفسار عام', max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
            ],
            options={
                'verbose_name': 'رسالة واردة',
                'verbose_name_plural': 'صندوق الرسائل الواردة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_ar', models.CharField(max_length=150, verbose_name='المسمى الوظيفي بالعربية')),
                ('role_en', models.CharField(max_length=150, verbose_name='المسمى الوظيفي بالإنجليزية')),
                ('company', models.CharField(max_length=150, verbose_name='اسم الشركة / المنظمة')),
                ('period_ar', models.CharField(default='2024 - الآن', max_length=100, verbose_name='الفترة بالعربية')),
                ('period_en', models.CharField(default='2024 - Present', max_length=100, verbose_name='الفترة بالإنجليزية')),
                ('desc_ar', models.TextField(verbose_name='وصف الإنجازات والمهام بالعربية')),
                ('desc_en', models.TextField(verbose_name='وصف الإنجازات والمهام بالإنجليزية')),
                ('skills', models.CharField(default='System Architecture, Kubernetes, High-Performance C++', max_length=300, verbose_name='التقنيات المستخدمة (مفصولة بفاصلة)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'محطة خبرة مهنية',
                'verbose_name_plural': 'مسار الخبرات والقيادة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='يوسف طارق', max_length=150, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(default='Yousif Tariq', max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('role_ar', models.CharField(default='مهندس أنظمة وبرمجيات متقدمة', max_length=200, verbose_name='المسمى الوظيفي بالعربية')),
                ('role_en', models.CharField(default='Lead Systems & Software Engineer', max_length=200, verbose_name='المسمى الوظيفي بالإنجليزية')),
                ('badge_ar', models.CharField(default='مهندس أنظمة وبرمجيات • Systems & Software Engineer', max_length=200, verbose_name='شارة التعريف بالعربية')),
                ('badge_en', models.CharField(default='Systems & Software Engineer', max_length=200, verbose_name='شارة التعريف بالإنجليزية')),
                ('bio_ar', models.TextField(default='مهندس برمجيات ونظم شغوف بهندسة البنى التحتية المتينة وتطوير حلول برمجية متكاملة تمزج بين الأداء الخارق وجمال التجربة الرقمية.', verbose_name='النبذة بالعربية')),
                ('bio_en', models.TextField(default='A passionate systems & software engineer dedicated to building resilient distributed infrastructures and scalable software solutions.', verbose_name='النبذة بالإنجليزية')),
                ('primary_photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='الصورة الشخصية الأساسية')),
                ('alter_ego_photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='الصورة الشخصية الثانية (Alter Ego)')),
                ('cta_primary_ar', models.CharField(default='ابدأ الغوص في المعمارية', max_length=100, verbose_name='نص الزر الرئيسي بالعربية')),
                ('cta_primary_en', models.CharField(default='Explore Architecture Dive', max_length=100, verbose_name='نص الزر الرئيسي بالإنجليزية')),
                ('cta_secondary_ar', models.CharField(default='إرسال إشارة اتصال', max_length=100, verbose_name='نص الزر الثانوي بالعربية')),
                ('cta_secondary_en', models.CharField(default='Transmit Signal', max_length=100, verbose_name='نص الزر الثانوي بالإنجليزية')),
                ('stat_1_val', models.CharField(default='+5', max_length=50, verbose_name='إحصائية 1 - القيمة')),
                ('stat_1_lbl_ar', models.CharField(default='سنوات الخبرة في الهندسة', max_length=100, verbose_name='إحصائية 1 - النص بالعربية')),
                ('stat_1_lbl_en', models.CharField(default='Years Engineering Experience', max_length=100, verbose_name='إحصائية 1 - النص بالإنجليزية')),
                ('stat_2_val', models.CharField(default='+28', max_length=50, verbose_name='إحصائية 2 - القيمة')),
                ('stat_2_lbl_ar', models.CharField(default='أنظمة ومشاريع منجزة', max_length=100, verbose_name='إحصائية 2 - النص بالعربية')),
                ('stat_2_lbl_en', models.CharField(default='Production Systems Built', max_length=100, verbose_name='إحصائية 2 - النص بالإنجليزية')),
                ('stat_3_val', models.CharField(default='< 5ms', max_length=50, verbose_name='إحصائية 3 - القيمة')),
                ('stat_3_lbl_ar', models.CharField(default='كفاءة وزمن استجابة أقل من', max_length=100, verbose_name='إحصائية 3 - النص بالعربية')),
                ('stat_3_lbl_en', models.CharField(default='Core Latency Target', max_length=100, verbose_name='إحصائية 3 - النص بالإنجليزية')),
                ('stat_4_val', models.CharField(default='99.9%', max_length=50, verbose_name='إحصائية 4 - القيمة')),
                ('stat_4_lbl_ar', models.CharField(default='جاهزية واستقرار النظم', max_length=100, verbose_name='إحصائية 4 - النص بالعربية')),
                ('stat_4_lbl_en', models.CharField(default='System Availability', max_length=100, verbose_name='إحصائية 4 - النص بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل هذا الملف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الملف الشخصي والواجهة الرئيسية (Hero)',
                'verbose_name_plural': 'الملف الشخصي والواجهة الرئيسية (Hero)',
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('category', models.CharField(default='Distributed Systems', max_length=100, verbose_name='تصنيف المشروع')),
                ('desc_ar', models.TextField(verbose_name='وصف المشروع بالعربية')),
                ('desc_en', models.TextField(verbose_name='وصف المشروع بالإنجليزية')),
                ('stat_throughput', models.CharField(default='1.2M ops/sec', max_length=50, verbose_name='مقياس الأداء / Throughput')),
                ('stat_latency', models.CharField(default='< 1.8ms', max_length=50, verbose_name='زمن التأخير / Latency')),
                ('stat_availability', models.CharField(default='99.999%', max_length=50, verbose_name='الجاهزية / Availability')),
                ('tags', models.CharField(default='C++20, Rust, gRPC', max_length=300, verbose_name='الوسوم التقنية (مفصولة بفاصلة)')),
                ('features_ar', models.TextField(help_text='اكتب كل ميزة في سطر منفصل', verbose_name='الميزات المعمارية بالعربية')),
                ('features_en', models.TextField(help_text='Each feature on a new line', verbose_name='الميزات المعمارية بالإنجليزية')),
                ('demo_url', models.URLField(blank=True, default='#', verbose_name='رابط المعاينة المباشرة')),
                ('github_url', models.URLField(blank=True, default='#', verbose_name='رابط كود المصدر (GitHub)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'مشروع بارز',
                'verbose_name_plural': 'المشاريع الكبرى',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='إعدادات المنظومة والموقع', max_length=150, verbose_name='عنوان الإعدادات')),
                ('email', models.EmailField(default='yousif.tariq@engineer.dev', max_length=254, verbose_name='البريد الرسمي')),
                ('location_ar', models.CharField(default='الرياض • متاح للعمل عن بعد وحول العالم', max_length=200, verbose_name='الموقع بالعربية')),
                ('location_en', models.CharField(default='Riyadh • Available for Global & Remote Challenges', max_length=200, verbose_name='الموقع بالإنجليزية')),
                ('status_ar', models.CharField(default='متاح حالياً للمشاريع والتحديات الهندسية المتقدمة 🟢', max_length=200, verbose_name='حالة التوفر بالعربية')),
                ('status_en', models.CharField(default='Currently Available for Advanced Systems & Architecture Roles 🟢', max_length=200, verbose_name='حالة التوفر بالإنجليزية')),
                ('terminal_title', models.CharField(default='yousif@quantum-core:~$ connect --secure', max_length=150, verbose_name='عنوان شاشة الأوامر')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع والتواصل',
                'verbose_name_plural': 'إعدادات الموقع والتواصل',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True, verbose_name='المعرف البرمجي (systems, distributed, software, data)')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم التصنيف بالعربية')),
                ('name_en', models.CharField(max_length=150, verbose_name='اسم التصنيف بالإنجليزية')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف مهارات',
                'verbose_name_plural': 'تصنيفات المهارات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المهارة أو التقنية')),
                ('level', models.PositiveIntegerField(default=85, verbose_name='نسبة الإتقان (1-100)%')),
                ('desc_ar', models.TextField(blank=True, verbose_name='الوصف والتفاصيل بالعربية')),
                ('desc_en', models.TextField(blank=True, verbose_name='الوصف والتفاصيل بالإنجليزية')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_app.skillcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مهارة تقنية',
                'verbose_name_plural': 'المهارات والتقنيات',
                'ordering': ['category', 'order'],
            },
        ),
    ]
