# Generated by Django 6.0.7 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان الـ IP')),
                ('device_id', models.CharField(db_index=True, max_length=120, verbose_name='معرف الجهاز الفريد')),
                ('user_agent', models.TextField(blank=True, verbose_name='بيانات المتصفح والنظام (User Agent)')),
                ('device_type', models.CharField(default='Desktop', max_length=50, verbose_name='نوع الجهاز (Mobile/Desktop/Tablet)')),
                ('browser', models.CharField(default='Unknown', max_length=100, verbose_name='المتصفح')),
                ('os', models.CharField(default='Unknown', max_length=100, verbose_name='نظام التشغيل')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='لغة التصفح')),
                ('screen_resolution', models.CharField(blank=True, max_length=50, verbose_name='دقة الشاشة')),
                ('referrer', models.URLField(blank=True, max_length=500, null=True, verbose_name='مصدر الزيارة (Referrer)')),
                ('path_visited', models.CharField(default='/', max_length=200, verbose_name='الصفحة / المسار')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ ووقت الزيارة')),
            ],
            options={
                'verbose_name': 'سجل زيارة جهاز',
                'verbose_name_plural': 'سجلات زيارات التطبيق (Analytics)',
                'ordering': ['-created_at'],
            },
        ),
    ]
