# Generated by Django 6.0.7 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(db_index=True, default='Unknown', max_length=100, verbose_name='المتصفح'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='device_type',
            field=models.CharField(db_index=True, default='Desktop', max_length=50, verbose_name='نوع الجهاز (Mobile/Desktop/Tablet)'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='language',
            field=models.CharField(db_index=True, default='en', max_length=10, verbose_name='لغة التصفح'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='os',
            field=models.CharField(db_index=True, default='Unknown', max_length=100, verbose_name='نظام التشغيل'),
        ),
    ]
