# Generated by Django 6.0.7 on 2026-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_visitorlog_browser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل زيارة جهاز', 'verbose_name_plural': 'سجلات زيارات التطبيق (Analytics & Geolocation)'},
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز الدولة'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='isp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مزود خدمة الإنترنت (ISP / Network)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='خط الطول (Longitude)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة / المحافظة'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='المنطقة الزمنية'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الدولة'),
        ),
    ]
